Add support for proper layer titles, authorization
B3Partners/tailormap-api pull request #139
Opened 2022-06-21 15:18 UTC by puckipedia

One PR as the authorization commit builds on top of the layer title commit. The layer title commit should be self-explanatory, so some details on the authorization commit:

To avoid the `n+1` issue with ORMs, this commit uses `EntityGraph`s to fetch most necessary components in one go, exchanging latency for bandwidth use. The SQL queries are visualised here to the best of my abilities:
```mermaid
flowchart TD
  %% query 1
  Application -->|findWithGeoservicesById| ApplicationLayer
  ApplicationLayer  -->|findWithGeoservicesById| GeoService

  %% query 2
  Level -->|findByLevelTree| Level

  %% query 3
  Level -->|findWithAuthorizationDataByIdIn| ApplicationLayer
  ApplicationLayer -->|findWithAuthorizationDataByIdIn| GeoService

  %% query 4
  %% just fetches ApplicationLayers that have not been fetched by previous queries?

  %% query 5
  ApplicationLayer -->|getStartLevels| StartLevel
  StartLevel -->|getStartLevels| Level

  %% query 6
  GeoService -->|findByServiceIdIn| Layer

  linkStyle 0,1 stroke:#ff9a56
  linkStyle 2 stroke:#ef7627
  linkStyle 3,4 stroke:#F5A9B8
  linkStyle 5,6 stroke:#b55690
  linkStyle 7 stroke:#5BCEFA
```

All of these queries, other than the native query (`findByLevelTree`) use methods on the respective entitiy's `JpaRepositories`,  with `@EntityGraph` as hints to Hibernate to fetch all necessary components.

The code filters out any `ApplicationLayer`, `Layer`, `GeoService`, or `Level` that has not been authorized to the current user's groups. However, if a `Level` contains one `Layer` that is filtered out, the `Level` it is in remains. This means that if a background `Layer` is not visible to the current user, it can still be selected in the viewer, but it will not show a proper map.

2022-06-21 16:05 UTC, mprins commented
@puckipedia Can you mention the relevant Jira tickets in the PR title / description as in eg. #133 so that the Jira tickets get moved to their new status

2022-07-03 10:01 UTC, mprins requested changes

2022-07-03 10:01 UTC, mprins commented on src/main/java/nl/b3p/tailormap/api/controller/MapController.java
> +            return ResponseEntity.status(HttpStatus.NOT_FOUND)
Ik zou hier een `throw new EntityNotFoundException(...)` gebruiken zodat het bestaande mechanisme van de ExceptionHandler in  `public ErrorResponse handleEntityNotFoundException(EntityNotFoundException exception) ` op https://github.com/B3Partners/tailormap-api/blob/a08ff5cebab53a7121ef6699ba5dfaae8d675967/src/main/java/nl/b3p/tailormap/api/controller/MapController.java#L142 wordt gebruikt

Nu is er duplicatie van de foutmelding waarbij er 1 wel wordt gelogd en de andere niet...

2022-07-15 13:37 UTC, matthijsln approved these changes

2022-07-15 13:59 UTC, mprins approved these changes

2022-07-15 13:59 UTC, merged