Improve authorization checks
B3Partners/tailormap-api pull request #223
Opened 2022-10-27 14:54 UTC by puckipedia

(see HTM-296)

Refactors the existing authorization checks into one `Service`, and uses this to add proper
authorization to the feature info endpoints, as well as adding `readers` support to `Application`.

Authorization code for the `MapController` is currently still separate, due to its specializations (it's designed to authorize an entire application worth of layers).

2022-11-01 12:50 UTC, mprins commented on src/main/java/nl/b3p/tailormap/api/controller/AppController.java
> -import nl.b3p.tailormap.api.security.AuthUtil;
it seems `nl.b3p.tailormap.api.security.AuthUtil` is no longer used anywhere, in that case it can/should be removed

2022-11-01 15:54 UTC, puckipedia commented on src/main/java/nl/b3p/tailormap/api/security/AuthorizationService.java
> +        Authentication authentication = SecurityContextHolder.getContext().getAuthentication();
A `null` authentication will now be considered equivalent to an anonymous token.

2022-11-07 20:14 UTC, mprins requested changes

2022-11-07 20:14 UTC, mprins commented on src/main/java/nl/b3p/tailormap/api/security/AuthorizationService.java
> +        Authentication authentication = SecurityContextHolder.getContext().getAuthentication();
There are more places in this class where this NPE possibility should be fixed

2022-11-08 09:31 UTC, merged