HTM-625: Send starting opacity in API
B3Partners/tailormap-api pull request #293
Opened 2023-01-05 14:37 UTC by puckipedia

(Do we want "opacity" to be sent as 0-100 instead of e.g. 0-1? The viewer uses 0-100, and persistence stores the transparency as 0-100; so it's probably fine.)

2023-01-05 15:35 UTC, matthijsln commented
The real resolution probably 0-255

2023-01-05 15:38 UTC, puckipedia commented
From what I can tell, the admin currently works in 0-100 (steps of 1), and this is what is stored in the database.

2023-01-05 15:48 UTC, matthijsln requested changes

2023-01-05 15:48 UTC, matthijsln commented on src/main/java/nl/b3p/tailormap/api/controller/MapController.java
> +            ClobElement transparencyElement = applicationLayer.getDetails().get("transparency");
Use streams and Optional

```
diff --git a/src/main/java/nl/b3p/tailormap/api/controller/MapController.java b/src/main/java/nl/b3p/tailormap/api/controller/MapController.java
index a9851702..edada560 100644
--- a/src/main/java/nl/b3p/tailormap/api/controller/MapController.java
+++ b/src/main/java/nl/b3p/tailormap/api/controller/MapController.java
@@ -23,6 +23,7 @@
 import nl.b3p.tailormap.api.repository.LevelRepository;
 import nl.b3p.tailormap.api.security.AuthorizationService;
 import nl.b3p.tailormap.api.util.ParseUtil;
+import nl.tailormap.viewer.config.ClobElement;
 import nl.tailormap.viewer.config.app.Application;
 import nl.tailormap.viewer.config.app.ApplicationLayer;
 import nl.tailormap.viewer.config.app.Level;
@@ -32,7 +33,6 @@
 import nl.tailormap.viewer.config.services.Layer;
 import nl.tailormap.viewer.config.services.TileService;
 import nl.tailormap.viewer.config.services.WMSService;
-import nl.tailormap.viewer.config.ClobElement;
 
 import org.apache.commons.lang3.StringUtils;
 import org.apache.commons.logging.Log;
@@ -461,6 +461,13 @@ && isAuthorized(
                 }
             }
 
+            int opacity =
+                    Optional.ofNullable(applicationLayer.getDetails().get("transparency"))
+                            .map(Object::toString)
+                            .map(Integer::parseInt)
+                            .map(transparency -> 100 - transparency)
+                            .orElse(0);
+
             AppLayer appLayer =
                     new AppLayer()
                             .id(applicationLayer.getId())
@@ -469,7 +476,7 @@ && isAuthorized(
                             .serviceId(applicationLayer.getService().getId())
                             .url(proxied ? getProxyUrl(geoService, a, applicationLayer) : null)
                             .visible(l.isChecked())
-                            .opacity(0)
+                            .opacity(opacity)
                             .maxScale(serviceLayer.getMaxScale())
                             .minScale(serviceLayer.getMinScale())
                             .legendImageUrl(legendImageUrl)
@@ -477,15 +484,6 @@ && isAuthorized(
                             .hiDpiSubstituteLayer(hiDpiSubstituteLayer)
                             .hasAttributes(!l.getApplicationLayer().getAttributes().isEmpty());
 
-            ClobElement transparencyElement = applicationLayer.getDetails().get("transparency");
-            if (transparencyElement != null) {
-                String transparency = transparencyElement.getValue();
-                try {
-                    appLayer.setOpacity(100 - Integer.parseInt(transparency));
-                } catch (NumberFormatException e) {
-                }
-            }
-
             mapResponse.addAppLayersItem(appLayer);
 
             Service.ServerTypeEnum serviceServerType =
```

2023-01-10 12:37 UTC, matthijsln approved these changes

2023-01-10 13:34 UTC, merged