[HTM-777] Add admin API to refresh feature source capabilities
B3Partners/tailormap-api pull request #468
Opened 2023-05-24 10:12 UTC by matthijsln

Do not refresh on @HandleBeforeSave event

2023-05-26 10:21 UTC, mprins requested changes

2023-05-26 10:21 UTC, mprins commented on src/main/java/nl/b3p/tailormap/api/controller/admin/FeatureSourceAdminController.java
> +    TMFeatureSource featureSource = featureSourceRepository.findById(id).orElse(null);
this could also use `orElseThrow(...)`

2023-05-26 10:21 UTC, mprins commented on src/main/resources/db/migration/V1__schema.sql
not sure why we need extra whitespace / reformatting in user_groups

2023-05-26 15:49 UTC, matthijsln commented on src/main/resources/db/migration/V1__schema.sql
overlooked those...

2023-06-02 09:30 UTC, mprins approved these changes

2023-06-02 09:30 UTC, merged