Update to add layer tree and some more properties
B3Partners/tailormap-api pull request #83
Opened 2022-03-31 15:00 UTC by matthijsln

HTM-247

2022-04-01 09:43 UTC, geertplaisier requested changes

2022-04-01 09:43 UTC, geertplaisier commented on src/main/resources/tailormap-api.yaml
> +        - noBaseLayerOption
Remove this

2022-04-01 09:43 UTC, geertplaisier commented on src/main/resources/tailormap-api.yaml
> +        - rootBaseLayerGroup
Rename these

2022-04-01 09:44 UTC, geertplaisier requested changes

2022-04-01 09:44 UTC, geertplaisier commented on src/main/resources/model.yaml
> +            type: integer
This type should be string, it references a LayerTreeNode id

2022-04-01 13:28 UTC, geertplaisier approved these changes

2022-04-01 13:35 UTC, mprins approved these changes
LGTM

2022-04-05 14:36 UTC, mprins commented
I think this should be merged into https://github.com/B3Partners/tailormap-api/pull/83 (if still needed and closed - it seems https://github.com/B3Partners/tailormap-api/commits/HTM-248-implement-api has all the commits of this branch + more)

2022-04-05 16:27 UTC, matthijsln commented
See #86.

2022-04-05 16:27 UTC, closed without merging

2022-04-06 09:51 UTC, mprins commented
duhh, I meant #86...